export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_INFO = 'GET_USER_INFO'

export const GET_USER_REPO_REQUEST = 'GET_USER_REPO_REQUEST'
export const GET_USER_REPO_INFO = 'GET_USER_REPO_INFO'

export const GET_USER_FILTER_REPO_REQUEST = 'GET_USER_FILTER_REPO_REQUEST'
export const GET_USER_FILTER_REPO_INFO = 'GET_USER_FILTER_REPO_INFO'

export const GET_REPO_STAR_GAZERS_REQUEST = 'GET_REPO_STAR_GAZERS_REQUEST'
export const GET_REPO_STAR_GAZERS_INFO = 'GET_REPO_STAR_GAZERS_INFO'

export const SET_ACTIVE_PAGE_REQUEST = 'SET_ACTIVE_PAGE_REQUEST'
export const GET_ACTIVE_PAGE_INFO = 'GET_ACTIVE_PAGE_INFO'

export const SET_FILTER_STRING = 'SET_FILTER_STRING'

export const SHOW_MESSAGE_REQUEST = 'SHOW_MESSAGE_REQUEST'
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const HIDE_MESSAGE = 'HIDE_MESSAGE'